[tools]
# languages
node = "latest"
python = "3.14.1"
# linters and tooling
actionlint = "latest"
jq = "latest"
lefthook = "latest"
markdownlint-cli2 = "latest"
ruff = "latest"
shellcheck = "latest"
yamllint = "latest"
